# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Sube una foto de no mas de 2mb y de una resoluci\xf3n maxima 1280x1280.', null=True, upload_to=b'')),
                ('headline', models.CharField(help_text='Breve description de hasta 200 caracteres.', max_length=200)),
                ('about', models.TextField(help_text='Cuentales a tus alumnos por que deberian tomar la clase contigo')),
                ('fee', models.FloatField(help_text='El monto minimo es $CL2.000 y maximo es $CL50.000 por hora')),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
