# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('front', '0002_slimcommentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slimcommentform',
            name='xtdcomment_ptr',
        ),
        migrations.DeleteModel(
            name='SlimCommentForm',
        ),
    ]
