# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_slimcommentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlimCommentForm',
            new_name='SlimComment',
        ),
    ]
