# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20161129_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(help_text='Cuentanos en que asignaturas quieres ser profesor', to='front.Skill'),
        ),
    ]
